export enum TxState {
  MESH_PENDING = 'MESH_PENDING',
  USDC_LOCKED = 'USDC_LOCKED',
  DISPATCHED = 'DISPATCHED',
  SETTLED = 'SETTLED',
  FAILED = 'FAILED',
  FAILED_DISPATCH = 'FAILED_DISPATCH',
  REFUND_QUEUED = 'REFUND_QUEUED',
  REFUNDED = 'REFUNDED',
}
